### ISSUE TITLE
Make release

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/bugsigdbr#61] opened 2024-10-17 15:12 UTC
@lwaldron @lgeistlinger I will do a release on zenodo.

**Comment by lgeistlinger** [comment] 2024-10-18 17:52
When making a release, my suggestion is to always have a senior member of the BugSigDB curation team in the loop. 
Especially the part of the data dump that is new, ie all studies that haven't been included in the previous release, would benefit from a careful quality control check. We have [previously documented a number of checks](https://github.com/waldronlab/bugsigdbr/issues/49) for key fields such as condition and body site, especially for cases where this annotation is missing, and the data quality and all downstream analysis would benefit if these fields were carefully reviewed at release time.

**Comment by jwokaty** [comment] 2024-10-18 18:47
@lgeistlinger thank you.

@cmirzayi Would you have time to review for the release or could you recommend someone who might be able to help next week? I'll select a commit for the release then run the tests in this package on it and it would be great if someone could inspect its quality from maybe midweek?

**Comment by cmirzayi** [comment] 2024-10-18 18:54
I can review next week.

**Comment by jwokaty** [comment] 2024-10-23 03:00
@cmirzayi Thank you. I want to propose https://github.com/waldronlab/BugSigDBExports/tree/f54d8fc3b99a80581d4ae0677ae22462967165ac as the release. I'm able to install, build, check it without issue. It does appear to have NAs in the Body and Condition. The number of rows appear correct. If there is a better commit, feel free to suggest.

**Comment by cmirzayi** [comment] 2024-10-23 03:51
@jwokaty Ok when do you need the review done by? Just need to prioritize my week.

**Comment by jwokaty** [comment] 2024-10-23 15:25
I think the code free happens on Friday, but I'm not sure what time. Things are tight for me too. If it's possible, maybe EOD tomorrow 10/24, but if not, maybe we can do it after the release. Let's discuss at the lab meeting tomorrow. I should have really started this earlier, so my apologies.

**Comment by cmirzayi** [comment] 2024-10-23 16:56
Ok sounds good. I have my IMMSA presentation tomorrow from 12-1 but I can block off tomorrow afternoon for focusing specifically on this.

And no worries. This is a hectic, wild, and altogether packed month. I totally get it. Looking forward to talking tomorrow!

**Comment by jwokaty** [comment] 2024-10-24 15:20
@cmirzayi This is the previous discussion about the release: https://github.com/waldronlab/bugsigdbr/issues/49. If you have any helpful notes to add, such as including unreviewed? items, please include in the discussion here so that we can later formalize this process. Thanks so much for your help!

**Comment by cmirzayi** [comment] 2024-10-24 18:43
All studies/experiments with missing conditions and body sites have been resolved in BugSigDB.

Studies with missing condition
Study 333 - Appears to be an issue with it not carrying forward from the previous experiment. Added.
Study 860 - Environmental study; entered condition as environmental factor.
Study 872 - Added spinal cord injury.
Study 1048 - This study is very complicated and I don't really understand it. Marking incomplete until it can be reviewed in detail.
Study 1104 - I don't have access to this article and I am skeptical of the curation. Marking as incomplete until it can be reviewed in detail.
Study 1107 - Curator added condition this morning.
Study 1139 - Recently added.

Studies with missing body site
Study 860- Environmental study; entered as "space surrounding organism" for lack of a better option.
Study 872 - Added feces.
Study 888, Experiment 49 - Wastewater experiment. Entered as "space surrounding organism" for lack of a better option.
Study 1048  - this study is very complicated and I don't really understand it. Marking incomplete until it can be reviewed in detail
Study 1107 - Recently added.

**Comment by cmirzayi** [comment] 2024-10-24 18:59
All studies present in https://zenodo.org/records/10627578 (previous release) are present in the candidate release.

**Comment by cmirzayi** [comment] 2024-10-24 19:08
84 signatures have been removed since the previous release. In the interest of time, I randomly selected 25 of them to check and they were all purposefully deleted due to curation reviews. I feel fairly confident that none of them are missing due to data integrity issues.
```[1] "bsdb:200/1/1"   "bsdb:246/3/1"   "bsdb:306/1/1"   "bsdb:306/1/2"   "bsdb:340/1/NA"  "bsdb:410/2/1"  
 [7] "bsdb:435/2/2"   "bsdb:468/2/1"   "bsdb:468/2/2"   "bsdb:468/3/1"   "bsdb:468/4/1"   "bsdb:468/5/1"  
[13] "bsdb:468/5/2"   "bsdb:497/2/1"   "bsdb:497/2/2"   "bsdb:520/1/1"   "bsdb:522/2/1"   "bsdb:522/2/2"  
[19] "bsdb:522/3/1"   "bsdb:522/3/2"   "bsdb:522/4/1"   "bsdb:522/4/2"   "bsdb:522/5/1"   "bsdb:522/5/2"  
[25] "bsdb:562/10/NA" "bsdb:563/3/NA"  "bsdb:563/5/NA"  "bsdb:563/7/NA"  "bsdb:572/2/NA"  "bsdb:583/1/3"  
[31] "bsdb:583/1/4"   "bsdb:583/1/5"   "bsdb:583/1/6"   "bsdb:602/1/NA"  "bsdb:607/2/1"   "bsdb:607/2/2"  
[37] "bsdb:607/3/1"   "bsdb:617/1/NA"  "bsdb:632/2/1"   "bsdb:632/2/2"   "bsdb:672/1/NA"  "bsdb:673/2/1"  
[43] "bsdb:673/3/1"   "bsdb:682/2/NA"  "bsdb:682/3/NA"  "bsdb:715/1/2"   "bsdb:715/3/2"   "bsdb:715/5/2"  
[49] "bsdb:721/2/3"   "bsdb:721/2/4"   "bsdb:721/2/5"   "bsdb:721/2/6"   "bsdb:779/1/2"   "bsdb:804/1/2"  
[55] "bsdb:805/1/NA"  "bsdb:812/2/3"   "bsdb:812/2/4"   "bsdb:812/2/5"   "bsdb:812/2/6"   "bsdb:822/1/2"  
[61] "bsdb:822/2/2"   "bsdb:822/3/2"   "bsdb:828/1/1"   "bsdb:828/1/2"   "bsdb:828/2/2"   "bsdb:828/3/NA" 
[67] "bsdb:845/2/1"   "bsdb:845/2/2"   "bsdb:845/3/1"   "bsdb:845/3/2"   "bsdb:845/4/1"   "bsdb:845/4/2"  
[73] "bsdb:845/5/1"   "bsdb:845/5/2"   "bsdb:845/6/1"   "bsdb:845/6/2"   "bsdb:859/1/NA"  "bsdb:859/2/NA" 
[79] "bsdb:859/3/NA"  "bsdb:859/4/1"   "bsdb:859/5/1"   "bsdb:859/5/2"   "bsdb:868/2/1"   "bsdb:868/2/2" ```

**Comment by cmirzayi** [comment] 2024-10-24 19:42
There's about 100 curations that aren't complete--usually because they have an experiment with no signature. Some of these are experiments with no differential abundance results while others were truly incomplete curations. I did my best to mark the ones that were incomplete from what I could tell.

``` [1] "Study 86"   "Study 306"  "Study 321"  "Study 426"  "Study 442"  "Study 443"  "Study 445"  "Study 457" 
 [9] "Study 458"  "Study 460"  "Study 463"  "Study 465"  "Study 467"  "Study 475"  "Study 484"  "Study 497" 
[17] "Study 504"  "Study 505"  "Study 515"  "Study 528"  "Study 574"  "Study 575"  "Study 581"  "Study 616" 
[25] "Study 619"  "Study 624"  "Study 642"  "Study 667"  "Study 672"  "Study 678"  "Study 683"  "Study 715" 
[33] "Study 755"  "Study 772"  "Study 789"  "Study 807"  "Study 812"  "Study 819"  "Study 828"  "Study 830" 
[41] "Study 840"  "Study 843"  "Study 845"  "Study 853"  "Study 861"  "Study 876"  "Study 877"  "Study 881" 
[49] "Study 884"  "Study 888"  "Study 892"  "Study 904"  "Study 911"  "Study 921"  "Study 947"  "Study 953" 
[57] "Study 955"  "Study 962"  "Study 963"  "Study 966"  "Study 971"  "Study 985"  "Study 991"  "Study 995" 
[65] "Study 1008" "Study 1014" "Study 1020" "Study 1022" "Study 1029" "Study 1032" "Study 1033" "Study 1041"
[73] "Study 1044" "Study 1048" "Study 1055" "Study 1063" "Study 1070" "Study 1074" "Study 1077" "Study 1083"
[81] "Study 1084" "Study 1086" "Study 1092" "Study 1097" "Study 1099" "Study 1100" "Study 1102" "Study 1107"
[89] "Study 1142" "Study 1146" "Study 1156" "Study 1159" "Study 1160" "Study 1170" "Study 1172"

**Comment by cmirzayi** [comment] 2024-10-24 19:59
Missing PMIDs
Study 501 - Not indexed in PubMed
Study 513 - Not Indexed in PubMed
Study 557 - Added
Study 562 - Body site typical "study"
Study 608 -  Body site typical "study"
Study 817 - Not indexed in PubMed
Study 836 - Added
Study 872 - Duplicate of Study 730
Study 879 - Not indexed in PubMed
Study 902 - Added
Study 906 - Added
Study 913 - Added
Study 965 - Added
Study 1078 - Not indexed in PubMed
Study 1139 - Added
Study 1159 - Duplicate of Study 775
Study 1172 - Duplicate of Study 1107
Study 1178 - Duplicate of Study 1151

**Comment by cmirzayi** [comment] 2024-10-24 20:03
Duplicate studies (and their accompanying experiments and signatures) have been deleted.

**Comment by cmirzayi** [comment] 2024-10-24 20:48
I made a few study and taxon tables as suggested by Levi. Everything looks good for now.

@jwokaty At this point I think I've exhausted what I can reasonably check this afternoon. I know there's still the duplicate signatures which was ran last time, but there's a lot of them--at least 40--and they take a long time to untangle. This is the sort of thing we would need multiple experienced project staff to divvy up and investigate.

**Comment by jwokaty** [comment] 2024-10-24 21:04
@cmirzayi Thanks for bringing us this far. Let's delay the release until we're able to resolve it. Maybe we can shoot for the first week in November--is that reasonable? Please keep me in the loop if I can support or if we're ready to cut the release.

**Comment by cmirzayi** [comment] 2024-10-25 13:32
@jwokaty That's reasonable. I can start looking through the duplicate signatures. I noticed that at least some of them seem to be from curations with significant errors. I will start reviewing 5 per day which should get us to the finish line.

**Comment by cmirzayi** [comment] 2024-10-25 14:52
I have eliminated about 20 of them which were all from the same study and just marked that study as incomplete for now. I am working to review the rest and am trying to get it done today.

**Comment by cmirzayi** [comment] 2024-10-25 18:35
@jwokaty I have reviewed all the studies because I really don't want to push that back this long. I just marked a bunch of studies as incomplete so they will not show up in the release. At this point, I think the review is done. What are the next steps?

**Comment by jwokaty** [comment] 2024-10-25 18:50
@cmirzayi Thanks for all of this and you're not holding it up. I initiated this too late. 

I believe I need to choose a new commit since you made some changes--if I understood correctly--then I'll pick the one after the github action run at the top of the hour. Do you think it needs to be spot checked or should I just make it the release? (I'm just paranoid because it's "live" and continuously edited.)

I will run the built in tests with bugsigdbr it then put it on zenodo and make changes to bugsigdbr. It won't be on the next report, but maybe I can make the changes for the Monday build report.

Thanks again for the quick turn around.

**Comment by cmirzayi** [comment] 2024-10-25 19:03
@jwokaty I should rerun my tests since it should be very fast. I will be prepared to do so once you identify a candidate release.

**Comment by cmirzayi** [comment] 2024-10-25 19:18
@jwokaty I just ran my checks on the 3 PM export. It looks good from my perspective.

**Closed as completed** 2024-10-27 06:45 UTC
